- name: Run precheck and create docker network
  become: true
  gather_facts: false
  hosts: all
  tasks:
    - name: run precheck
      include_tasks: precheck.yaml

    - name: Prepare docker network
      community.docker.docker_network:
          name: "{{ docker_network }}"

- name: Prepare configs
  become: true
  gather_facts: false
  hosts: all
  tasks:
    - name: run prepare configs
      include_tasks: prepare_configs.yml

- name: Deploy services
  become: true
  gather_facts: false
  hosts: all
  tasks:
    - name: run deploy service
      include_tasks: deploy_service.yml