---
- name: Prepare configs
  ansible.builtin.file:
    path: "{{ config_path }}/db"
    state: directory

- name: Copy config
  ansible.builtin.copy:
    src: "db"
    dest: "{{ config_path }}"

- name: Deploy postgres container
  community.docker.docker_container:
    name: "{{ postgres_image.name }}"
    image: "{{ postgres_image.repository }}:{{ postgres_image.version }}"
    env: "{{ postgres_image.env }}"
    volumes:
      - "{{ config_path }}/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z"
      - "{{ config_path }}/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z"
      - "{{ config_path }}/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z"
      - "{{ config_path }}/db/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql:Z"
      - "{{ config_path }}/db/data:/var/lib/postgresql/data:Z"
      - "{{ config_path }}/db/_supabase.sql:/docker-entrypoint-initdb.d/migrations/97-_supabase.sql:Z"
      - "{{ config_path }}/db/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql:Z"
      - "{{ config_path }}/db/pooler.sql:/docker-entrypoint-initdb.d/migrations/99-pooler.sql:Z"
    networks:
      - name: supabase_net